#ifndef PINS_H_
#define PINS_H_

#include <avr/io.h>

#define BATTERY_SENSE		PINA0

#define RIGHT_MOTOR_AIN1	PIND5
#define RIGHT_MOTOR_AIN2 	PINC0
#define RIGHT_MOTOR_SIGNAL	PIND7
#define LEFT_MOTOR_AIN1		PIND3
#define LEFT_MOTOR_AIN2 	PINC2
#define LEFT_MOTOR_SIGNAL	PIND6

#define DISTANCE_SENSOR		PINA7
#define DISTANCE_EMITTER	PINA6

#define TRANSMIT_PIN		PINA4
#define RECEIVE_PIN			PINA3

#define LIGHT_SENSOR		PIND5

#define BUZZER_PIN			PINB4

#define RED_LED				PINE2
#define GREEN_LED			PINE3
#define BLUE_LED			PINE4

#endif